name: OGP Dependencies Checker

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  build:
    # プルリクエストに dependencies ラベルを付けたとき
    # dependencies ラベルがついている状態で、 Push したとき
    if: |
      ((github.event.action == 'labeled') &&
        (github.event.label.name == 'ogp-dependencies')) ||
      ((github.event.action == 'synchronize') &&
        contains(github.event.pull_request.labels.*.name, 'ogp-dependencies'))

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci
        run: npm ci
      - name: Test
        run: npm run test
        env:
          CI: true
